services:
  backend:
    build:
      context: ./backend
    container_name: triage-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    command: python -m src.main

  frontend:
    build:
      context: ./frontend
    container_name: triage-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0



